config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :people
  resources :sales
  resources :games
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person

  validates :street, :number, presence: true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :scores, dependent: :destroy
  has_many :players, through: :scores

  accepts_nested_attributes_for :scores, allow_destroy: true
  accepts_nested_attributes_for :players

  validates :name, presence: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :addresses, dependent: :destroy
  accepts_nested_attributes_for :addresses, allow_destroy: true

  validates :name, presence: true
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :scores
  has_many :games, through: :scores
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :sales
  has_many :sellers, through: :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :seller
  belongs_to :product

  validates :seller_id, :product_id, :quantity, presence: true
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :game
  belongs_to :player

  accepts_nested_attributes_for :player

  validates :value, :player_id, presence: true
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_many :sales
  has_many :products, through: :sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :initialize_game, only: [:new, :create]
  before_action :load_game, only: [:edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def create
    if @game.update_attributes(game_params)
      redirect_to games_path
    else
      render 'new'
    end
  end

  def update
    if @game.update_attributes(game_params)
      redirect_to games_path
    else
      render 'edit'
    end
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  private

  def initialize_game
    @game = Game.new
  end

  def load_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(
      :name,
      scores_attributes: [:id, :value, :player_id, :_destroy]
    )
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render 'new'
    end
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(person_params)
      redirect_to people_path
    else
      render 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:name, addresses_attributes: [:id, :number, :street, :_destroy])
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :initialize_sale, only: [:new, :create]
  before_action :load_sale, only: [:edit, :update, :destroy]

  def index
    @sales = Sale.all
  end

  def create
    if @sale.update_attributes(sale_params)
      redirect_to sales_path
    else
      render 'new'
    end
  end

  def update
    if @sale.update_attributes(sale_params)
      redirect_to sales_path
    else
      render 'edit'
    end
  end

  def destroy
    @sale.destroy
    redirect_to sales_path
  end

  private

  def initialize_sale
    @sale = Sale.new
  end

  def load_sale
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:seller_id, :product_id, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Exemplos</h1>
<ul>
  <li>Person has_many Address (1xN) - <%= link_to 'exemplo', people_path %></li>
  <li>Seller has_many Products and Products has_many Sellers (NxN) - <%= link_to 'exemplo', sales_path %></li>
  <li>Game has_many Players and Players has_many Games (NxN) - <%= link_to 'exemplo', games_path %></li>
</ul>

app/views/games/_form.html.erb
<%= simple_form_for @game, wrapper: :vertical_form do |f|%>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= content_tag(:div, id: 'scores') do %>
    <%= f.simple_fields_for :scores do |scores_form| %>
      <%= render 'score_fields', f: scores_form %>
    <% end %>
    <%= link_to_add_association 'add score', f, :scores, class: 'btn btn-primary' %>
  <% end %>

  <%= f.button :submit %>
  <%= link_to 'Voltar', games_path %>
<% end %>

app/views/games/_score_fields.html.erb
<%= content_tag(:div, class: "col-md-12 nested-fields") do %>
  <%= f.input :value, wrapper_html: { class: 'col-xs-3' }  %>

  <%= f.input :player_id, collection: Player.all, wrapper_html: { class: 'col-xs-3' } %>

  <%= link_to_remove_association '', f, class: 'glyphicon glyphicon-remove' %>
<% end %>

app/views/games/edit.html.erb
<%= render 'form' %>

app/views/games/index.html.erb
<table class="table">
<caption>Games <%= link_to 'new', new_game_path %></caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Players</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td>
          <% game.scores.each do |score|%>
            <%= score.player.name %> - <%= score.value %> <br>
          <% end %>
        </td>
        <td>
          <%= link_to 'edit', edit_game_path(game) %>
          <%= link_to 'remove', game_path(game), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<%= render 'form' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Complex Forms" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Complex Forms" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/people/_address_fields.html.erb
<%= content_tag(:div, class: "col-md-12 nested-fields") do %>
  <%= f.input :street, wrapper_html: { class: 'col-xs-3' }  %>
  <%= f.input :number, wrapper_html: { class: 'col-xs-3' } %>
  <%= link_to_remove_association '', f, class: 'glyphicon glyphicon-remove' %>
<% end %>

app/views/people/_form.erb
<%= simple_form_for @person, wrapper: :vertical_form do |f|%>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= content_tag(:div, id: 'addresses') do %>
    <%= f.simple_fields_for :addresses do |addresses_form| %>
      <%= render 'address_fields', f: addresses_form %>
    <% end %>
    <%= link_to_add_association 'add address', f, :addresses, class: 'btn btn-primary' %>
  <% end %>

  <%= f.button :submit %>
  <%= link_to 'Voltar', people_path %>
<% end %>

app/views/people/_form.html.erb
<%= simple_form_for @person, wrapper: :vertical_form do |f|%>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= content_tag(:div, id: 'addresses') do %>
    <%= f.simple_fields_for :addresses do |addresses_form| %>
      <%= render 'address_fields', f: addresses_form %>
    <% end %>
    <%= link_to_add_association 'add address', f, :addresses, class: 'btn btn-primary' %>
  <% end %>

  <%= f.button :submit %>
  <%= link_to 'Voltar', people_path %>
<% end %>

app/views/people/edit.html.erb
<%= render 'form'%>

app/views/people/index.html.erb
<table class="table">
<caption>People <%= link_to 'new', new_person_path %></caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'edit', edit_person_path(person) %> <%= link_to 'remove', person_path(person), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<%= render 'form'%>

app/views/sales/_form.html.erb
<%= simple_form_for @sale, wrapper: :vertical_form do |f|%>
  <%= f.error_notification %>

  <%= f.input :seller_id, collection: Seller.all %>
  <%= f.input :product_id, collection: Product.all %>
  <%= f.input :quantity %>

  <%= f.button :submit %>
  <%= link_to 'Voltar', sales_path %>
<% end %>

app/views/sales/index.html.erb
<table class="table">
<caption>Sales <%= link_to 'new', new_sale_path %></caption>
  <thead>
    <tr>
      <th>Seller</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.seller.name %></td>
        <td><%= sale.product.name %></td>
        <td><%= sale.quantity%></td>
        <td>
          <%= link_to 'edit', edit_sale_path(sale) %>
          <%= link_to 'remove', sale_path(sale), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>